name: litup
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.3.2
  intl: ^0.20.2
  sizer: ^3.1.3
  font_awesome_flutter: ^10.7.0
  animations: ^2.1.0
  curved_navigation_bar: ^1.0.6
  animate_do: ^4.2.0
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  google_sign_in: ^5.4.2
  shared_preferences: ^2.5.3
  cloud_firestore: ^6.0.3
  firebase_storage: ^13.0.3
  image_picker: ^1.2.0
  share_plus: ^12.0.1
  google_generative_ai: ^0.4.7
  http: ^1.5.0
  audioplayers: ^6.5.1
  flutter_fortune_wheel: ^1.3.2
  sqflite: ^2.4.2
  path: ^1.9.1
  qr_flutter: ^4.0.0
  path_provider: ^2.1.5
  mobile_scanner: ^7.1.2
  smooth_page_indicator: ^1.2.1
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/DummyProfile.webp
    - assets/default_song.webp
    - assets/DummyParty.webp
    - assets/animations/
